### ISSUE TITLE
This library increase app size

### ISSUE THREAD

**Issue by erfansajjadie** [pusheco/pushe-flutter#10]
با سلام 
راهی برای کاهش حجم اپ بعد از اضافه کردن این کتابخانه وجود ندارد؟

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام

لایبرری‌های اصلی که ساختمان پلاگین پوشه رو تشکیل می‌دن:

- FirebaseMessaging
- RxJava2
- تعدادی لایبرری از Jetpack مثل WorkManager

هستند که بخش خوبی از حجم SDK رو شامل میشن. در مورد FirebaseMessaging و Jetpack کاری نمیشه کرد اما برای RxJava ما یه لایبرری کاستوم طراحی کردیم که فقط مقداری که نیاز بوده از RxJava برداشته شده و مابقی حذف شده. 

تنها راهی که می‌تونید برای کاهش حجم استفاده کنید Proguard هست که می‌تونید کدهای استفاده نشده رو حذف و کد موجود رو obfuscate کنید.

</div>
