### ISSUE TITLE
[ERROR]: پوشه آیدی را چگونه دریافت کنم؟

### ISSUE THREAD

**Issue by onyxtm** [pusheco/pushe-flutter#11]
<div dir='rtl'>
سلام، من در فلاتر میخوام که پوشه آیدی کاربر رو دریافت کنم و نمیدونم چه فانکشنی این آیدی رومیده.
و اینکه ممکنه androidId با pusheId یکی باشد؟
</div>

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
پوشه‌آی‌دی توی نسخه‌ی ۲.۰.۰ منسوخ شده و در نسخه‌های نهایی دیگه استفاده نمیشه شما باید از شناسه‌های جایگزین استفاده کنید.

![image](https://user-images.githubusercontent.com/21319971/80118465-ae5e5980-859d-11ea-82e3-af547e5b9718.png)


در مورد شناسه‌ها توی [داکیومنت‌ ](http://docs.pushe.co/docs/flutter/unification)توضیحات کاملی داده شده. در صورتی که اون توضیحات کافی نبودن لطفا ایشو رو باز کنید و سوال رو مطرح کنید.

</div>
