### ISSUE TITLE
❓ [ERROR]: 

### ISSUE THREAD

**Issue by onyxtm** [pusheco/pushe-flutter#12]
<div dir='rtl'>

Execution failed for task ':app:processDebugManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: java.io.FileNotFoundException: D:\..\APP_NAME\build\pushe_flutter\intermediates\library_manifest\debug\AndroidManifest.xml (The system cannot find the path specified)

من با این خطا مواجه میشم چیکار کنم
</div>

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
لطفا مطابق تمپلیت موارد خواسته شده رو به شرح اضافه کنید و همچنین استک‌تریس رو به طور کامل ارسال کنید.

</div>
