### ISSUE TITLE
❓ [ERROR]: Compile error in v2.4.1

### ISSUE THREAD

**Issue by sb996** [pusheco/pushe-flutter#17]
سلام با نصب نسخه جدید با این ارور مواجه شدم ممنون میشم راهنمایی کنید.

```
pushe_flutter-2.4.1\android\src\main\kotlin\co\pushe\plus\flutter\PusheChandler.kt: (606, 19):
  Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type String?
```

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام.
من این ایشو رو درستش کردم و **2.4.2** رو منتشر کردم.
ممنون میشم بگید اپتون بخش اندرویدش با جاوا پیاده‌سازی شده یا کاتلین. اگر کاتلین هست چه ورژنی از کاتلین.

</div>

[**Pushe_flutter:2.4.2**](https://pub.dev/packages/pushe_flutter/changelog#242)

**Comment by mahdi-malv** [comment]
@sb996 آیا با ۲.۴.۲ مشکل حل شد؟

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

@sb996 
من کماکان نتونستم این خطا رو تولید کنم که رفعش کنم. ممنون میشم راهنمایی کنید که بتونم reproduce کنم این مورد رو.

</div>

**Comment by mahdi-malv** [comment]
درود
من این ایشو رو میبندم
در صورتی که مشکل وجود داشت یا مشکلی مشابه پیش اومد لطفا ایشو رو باز کنید
