### ISSUE TITLE
🚀 [FEATURE]: Migrate to null-safety

### ISSUE THREAD

**Issue by Tokenizer94** [pusheco/pushe-flutter#18]
When you will migrate to the null-safety?

**Comment by bokanian** [comment]
please migrate to Null safety!

**Comment by mahdi-malv** [comment]
Hey

Thanks for reaching out.

Migration to **Null-safety** in progress

Here's first release of the plugin : [**Pushe_flutter:2.5.1-nullsafety.0**](https://pub.dev/packages/pushe_flutter/versions/2.5.1-nullsafety.0)

Stable release will happen soon.

**Comment by vahidpourmohamad** [comment]
so many warnings in Pushe_fluter:2.5.1-nullsafety.1

**Comment by elyas-dev** [comment]
please migrate to the Null safety as soon as possible

**Comment by mahdi-malv** [comment]
`2.5.1` is null-safe.
