### ISSUE TITLE
پوشه از فلاتروب پشتیبانی می‌کند؟ ❓ [ERROR]: 

### ISSUE THREAD

**Issue by Hadi7546** [pusheco/pushe-flutter#20]
پوشه و فلاتروب؟

**Comment by mahdi-malv** [comment]
درود

می‌تونید با مطالعه‌ی این مقاله در مورد این سوالتون اطلاعات بیشتری کسب کنید

[**Add Pushe web-push to a Flutter website**](https://malv.medium.com/add-pushe-web-push-to-a-flutter-website-a9b1ab736e57)
