### ISSUE TITLE
❓ [ERROR]: Could not GET 'https://dl.bintray.com/pushe/preview/androidx/lifecycle/lifecycle-common-java8/2.3.1/lifecycle-common-java8-2.3.1.pom'

### ISSUE THREAD

**Issue by mohammadPezeshki1994** [pusheco/pushe-flutter#26]
<div dir='rtl'>

**شرح خطا**
در زمان اضافه کردن پوشه به پروژه های جدید و همچنین پروژه های قبلی در زمان اجرا کردن این خطا رخ میدهد

**لاگ خطا**
</div>

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve androidx.lifecycle:lifecycle-common-java8:2.3.1.
     Required by:
         project :app > project :pushe_flutter
      > Could not resolve androidx.lifecycle:lifecycle-common-java8:2.3.1.
         > Could not get resource 'https://dl.bintray.com/pushe/preview/androidx/lifecycle/lifecycle-common-java8/2.3.1/lifecycle-common-java8-2.3.1.pom'.
            > Could not GET 'https://dl.bintray.com/pushe/preview/androidx/lifecycle/lifecycle-common-java8/2.3.1/lifecycle-common-java8-2.3.1.pom'. Received status code 403 from server: Forbidden
   > Could not resolve androidx.lifecycle:lifecycle-common-java8:2.3.1.
     Required by:
         project :app > project :pushe_flutter > io.flutter:flutter_embedding_debug:1.0.0-91c9fc8fe011352879e3bb6660966eafc0847233
      > Could not resolve androidx.lifecycle:lifecycle-common-java8:2.3.1.
         > Could not get resource 'https://dl.bintray.com/pushe/preview/androidx/lifecycle/lifecycle-common-java8/2.3.1/lifecycle-common-java8-2.3.1.pom'.
            > Could not GET 'https://dl.bintray.com/pushe/preview/androidx/lifecycle/lifecycle-common-java8/2.3.1/lifecycle-common-java8-2.3.1.pom'. Received status code 403 from server: Forbidden
   > Could not resolve androidx.fragment:fragment:1.2.2.
     Required by:
         project :app > project :pushe_flutter > io.flutter:flutter_embedding_debug:1.0.0-91c9fc8fe011352879e3bb6660966eafc0847233
         project :app > project :pushe_flutter > co.pushe.plus:base:2.5.0 > co.pushe.plus:notification:2.5.0 > androidx.appcompat:appcompat:1.1.0
      > Could not resolve androidx.fragment:fragment:1.2.2.
         > Could not get resource 'https://dl.bintray.com/pushe/preview/androidx/fragment/fragment/1.2.2/fragment-1.2.2.pom'.
            > Could not GET 'https://dl.bintray.com/pushe/preview/androidx/fragment/fragment/1.2.2/fragment-1.2.2.pom'. Received status code 403 from server: Forbidden
   > Could not resolve androidx.work:work-runtime-ktx:2.5.0.
     Required by:
         project :app > project :pushe_flutter > co.pushe.plus:inappmessaging:2.5.0
         project :app > project :pushe_flutter > co.pushe.plus:base:2.5.0 > co.pushe.plus:core:2.5.0
         project :app > project :pushe_flutter > co.pushe.plus:base:2.5.0 > co.pushe.plus:notification:2.5.0
         project :app > project :pushe_flutter > co.pushe.plus:base:2.5.0 > co.pushe.plus:datalytics:2.5.0
         project :app > project :pushe_flutter > co.pushe.plus:base:2.5.0 > co.pushe.plus:analytics:2.5.0
         project :app > project :pushe_flutter > co.pushe.plus:base:2.5.0 > co.pushe.plus:sentry:2.5.0
      > Could not resolve androidx.work:work-runtime-ktx:2.5.0.
         > Could not get resource 'https://dl.bintray.com/pushe/preview/androidx/work/work-runtime-ktx/2.5.0/work-runtime-ktx-2.5.0.pom'.
            > Could not GET 'https://dl.bintray.com/pushe/preview/androidx/work/work-runtime-ktx/2.5.0/work-runtime-ktx-2.5.0.pom'. Received status code 403 from server: Forbidden
   > Could not resolve androidx.work:work-rxjava2:2.5.0.
     Required by:
         project :app > project :pushe_flutter > co.pushe.plus:inappmessaging:2.5.0
         project :app > project :pushe_flutter > co.pushe.plus:base:2.5.0 > co.pushe.plus:core:2.5.0
         project :app > project :pushe_flutter > co.pushe.plus:base:2.5.0 > co.pushe.plus:notification:2.5.0
         project :app > project :pushe_flutter > co.pushe.plus:base:2.5.0 > co.pushe.plus:datalytics:2.5.0
         project :app > project :pushe_flutter > co.pushe.plus:base:2.5.0 > co.pushe.plus:analytics:2.5.0
         project :app > project :pushe_flutter > co.pushe.plus:base:2.5.0 > co.pushe.plus:sentry:2.5.0
      > Could not resolve androidx.work:work-rxjava2:2.5.0.
         > Could not get resource 'https://dl.bintray.com/pushe/preview/androidx/work/work-rxjava2/2.5.0/work-rxjava2-2.5.0.pom'.
            > Could not GET 'https://dl.bintray.com/pushe/preview/androidx/work/work-rxjava2/2.5.0/work-rxjava2-2.5.0.pom'. Received status code 403 from server: Forbidden
   > Could not resolve androidx.lifecycle:lifecycle-process:2.3.0.
     Required by:
         project :app > project :pushe_flutter > co.pushe.plus:base:2.5.0 > co.pushe.plus:core:2.5.0
      > Could not resolve androidx.lifecycle:lifecycle-process:2.3.0.
         > Could not get resource 'https://dl.bintray.com/pushe/preview/androidx/lifecycle/lifecycle-process/2.3.0/lifecycle-process-2.3.0.pom'.
            > Could not GET 'https://dl.bintray.com/pushe/preview/androidx/lifecycle/lifecycle-process/2.3.0/lifecycle-process-2.3.0.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.google.firebase:firebase-messaging:21.0.0.
     Required by:
         project :app > project :pushe_flutter > co.pushe.plus:base:2.5.0 > co.pushe.plus:fcm:2.5.0
      > Could not resolve com.google.firebase:firebase-messaging:21.0.0.
         > Could not get resource 'https://dl.bintray.com/pushe/preview/com/google/firebase/firebase-messaging/21.0.0/firebase-messaging-21.0.0.pom'.
            > Could not GET 'https://dl.bintray.com/pushe/preview/com/google/firebase/firebase-messaging/21.0.0/firebase-messaging-21.0.0.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.google.android.gms:play-services-ads-identifier:17.0.0.
     Required by:
         project :app > project :pushe_flutter > co.pushe.plus:base:2.5.0 > co.pushe.plus:fcm:2.5.0
      > Could not resolve com.google.android.gms:play-services-ads-identifier:17.0.0.
         > Could not get resource 'https://dl.bintray.com/pushe/preview/com/google/android/gms/play-services-ads-identifier/17.0.0/play-services-ads-identifier-17.0.0.pom'.
            > Could not GET 'https://dl.bintray.com/pushe/preview/com/google/android/gms/play-services-ads-identifier/17.0.0/play-services-ads-identifier-17.0.0.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.google.android.gms:play-services-location:18.0.0.
     Required by:
         project :app > project :pushe_flutter > co.pushe.plus:base:2.5.0 > co.pushe.plus:fcm:2.5.0
      > Could not resolve com.google.android.gms:play-services-location:18.0.0.
         > Could not get resource 'https://dl.bintray.com/pushe/preview/com/google/android/gms/play-services-location/18.0.0/play-services-location-18.0.0.pom'.
            > Could not GET 'https://dl.bintray.com/pushe/preview/com/google/android/gms/play-services-location/18.0.0/play-services-location-18.0.0.pom'. Received status code 403 from server: Forbidden
   > Could not resolve androidx.lifecycle:lifecycle-extensions:2.2.0.
     Required by:
         project :app > project :pushe_flutter > co.pushe.plus:base:2.5.0 > co.pushe.plus:notification:2.5.0
      > Could not resolve androidx.lifecycle:lifecycle-extensions:2.2.0.
         > Could not get resource 'https://dl.bintray.com/pushe/preview/androidx/lifecycle/lifecycle-extensions/2.2.0/lifecycle-extensions-2.2.0.pom'.
            > Could not GET 'https://dl.bintray.com/pushe/preview/androidx/lifecycle/lifecycle-extensions/2.2.0/lifecycle-extensions-2.2.0.pom'. Received status code 403 from server: Forbidden
   > Could not resolve androidx.media:media:1.1.0.
     Required by:
         project :app > project :pushe_flutter > co.pushe.plus:base:2.5.0 > co.pushe.plus:analytics:2.5.0
      > Could not resolve androidx.media:media:1.1.0.
         > Could not get resource 'https://dl.bintray.com/pushe/preview/androidx/media/media/1.1.0/media-1.1.0.pom'.
            > Could not GET 'https://dl.bintray.com/pushe/preview/androidx/media/media/1.1.0/media-1.1.0.pom'. Received status code 403 from server: Forbidden
   > Could not resolve androidx.fragment:fragment:1.2.2.
     Required by:
         project :app > project :pushe_flutter > co.pushe.plus:base:2.5.0 > co.pushe.plus:analytics:2.5.0
      > Could not resolve androidx.fragment:fragment:1.2.2.
         > Could not get resource 'https://dl.bintray.com/pushe/preview/androidx/fragment/fragment/1.2.2/fragment-1.2.2.pom'.
            > Could not GET 'https://dl.bintray.com/pushe/preview/androidx/fragment/fragment/1.2.2/fragment-1.2.2.pom'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

<div dir='rtl'>

**اطلاعات محیط تست**
- pushe_flutter: ^2.5.0
- Flutter 2.2.2
- OS  (Android)
- TargetSDK/CompileSDK (Android) : 30

</div>

**Comment by mahdi-malv** [comment]
@mohammadPezesh1994 مشکل حل شد؟

**Comment by mohammadPezesh1994** [comment]
بله مشکل از ثابت نبودن نت بود
تغییر دادم اوکی شد

**Comment by mohammadPezesh1994** [comment]
با سلام
من یک پروژه فلاتر دارم و الان نوتیفیکیشن واسه اندروید اوکی هست ولی واسه آی
او اس نه
تنها چیزی که اضافه نکردم واسه آی او اس NotificationService هست که نوشته
بودید اگر عکس یا فیلم در پروژه داریم اضافه کنیم
اروری که به من میده اینه Fail to read values in CFPrefsPlistSource هست سرچ
هم میکنم چیزه خاصی نیس لطفا راهنمایی کتید نمیدونم واقعا مشکل از کجاست
groupsId هم چک کردم اوکی بود خم اونی با اونی که به info.plist اضافه کردم

متشکر

**Comment by mahdi-malv** [comment]
Issue was first fixed in `2.5.1-nullsafety1`. Finally up and running in `2.5.1`
