### ISSUE TITLE
🐛 [BUG]: Could not resolve com.google.android.gms:play-services-location:16.+.

### ISSUE THREAD

**Issue by hossein626** [pusheco/pushe-flutter#29]
<div dir='rtl'>

[//]: # ([BUG] و اموجی در تیتر برای وضوح مشکل ترجیحا باقی بماند)
[//]: # (لطفا حتما تمپلیت را رعایت کنید تا مشکل به خوبی توضیح داده شود و متون تمپلیت را پاک نکنید)

**شرح باگ**
خطا در بیلد برنامه بعد از اضافه کردن پکیج پوشه

[//]: # (در صورتی که نصب ثبت نمی‌شود لطفا به مستندات مراجعه کنید و خطاها را مطالعه نمایید)
[//]: # (برای اضافه‌کردن کد آن‌را خارج از بلاک div قرار دهید تا سمت راست قرار نگیرد)

**تولید مجدد باگ**
- add pushe_flutter: ^2.5.0 to pubspec.yaml
- run pub get
- debug project

**اطلاعات محیط تست**
- android
- version ^2.5.0
- 22/30 (For Android)
- mac os

**لاگ خطا در لاگ‌کت**

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.google.android.gms:play-services-location:16.+.
     Required by:
         project :app > project :location
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Unable to load Maven meta-data from https://dl.bintray.com/pushe/preview/com/google/android/gms/play-services-location/maven-metadata.xml.
            > Could not get resource 'https://dl.bintray.com/pushe/preview/com/google/android/gms/play-services-location/maven-metadata.xml'.
               > Could not GET 'https://dl.bintray.com/pushe/preview/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**اطلاعات اضافی**

Flutter version 2.5.0 channel stable
classpath 'com.android.tools.build:gradle:4.1.0'

</div>

**Comment by mahdi-malv** [comment]
سلام
بابت تاخیر عذرخواهی میکنم

این مشکل توی nullsafetyها حل شده

https://pub.dev/packages/pushe_flutter/versions/2.5.1-nullsafety.1

به زودی نسخه‌ی استبل هم منتشر میشه
