### ISSUE TITLE
همکارانتون در پوشه متاسفانه پاسخگو نیستن 

### ISSUE THREAD

**Issue by abolfazl2643** [pusheco/pushe-flutter#31]
سلام

مدتی هست که سرویس پوشه رو به اپمون اضافه کردیم  اما بدلیل محدودیت های هواوی طبق داکیومنت پوشه به پشتیبانی درخواست دادیم که کد مربوط به هواوی رو برام بفرستن ولی هنوز بعد از ده روز بهمون جوابی داده نشده

متوجه هستم که اینجا جاش نیست ولی نه تلفن پاسخ داده میشه نه ایمیل

باتشکر

**Comment by mahdi-malv** [comment]
سلام
ممنون که اطلاع دادید
من پیگیری می‌کنم

**Comment by abolfazl2643** [comment]
ممنونم
