### ISSUE TITLE
❓ [ERROR]: Incompatible with Flutter 3.0 bridge APIs

### ISSUE THREAD

**Issue by mdpe-ir** [pusheco/pushe-flutter#35]
<div dir='rtl'>

[//]: # ([ERROR] و اموجی در تیتر برای وضوح مشکل ترجیحا باقی بماند)
[//]: # (لطفا حتما تمپلیت را رعایت کنید تا مشکل به خوبی توضیح داده شود و متون تمپلیت را پاک نکنید)

**شرح خطا**
سلام وقت بخیر
هنگام اجرا یا بیلد پروژه با خطای : 
` Type mismatch: inferred type is FlutterPluginRegistry? but PluginRegistry was expected`

مواجه میشوم.

[//]: # (در صورتی که نصب شما ثبت نمی‌شود لطفا خطاهای مستندات را مطالعه کنید)
[//]: # (برای اضافه‌کردن کد آن را از بلاک div خارج کنید تا سمت راست قرار نگیرد)

**لاگ خطا**
لاگی که در لاگ‌کت هنگام رخ‌دادن خطا چاپ می‌شود. متن کامل استک‌تریس را چاپ کنید.

</div>

```
pub.dartlang.org\pushe_flutter-2.6.0\android\src\main\kotlin\co\pushe\plus\flutter\PusheNotificationListener.kt: (271, 52): Type mismatch: inferred type is FlutterPluginRegistry? but PluginRegistry was expecte
```

<div dir='rtl'>

**اطلاعات محیط تست**
- نسخه‌ی پوشه یا پلاگین : pushe_flutter: ^2.6.0
- نسخه‌ی فریم‌ورک : flutter 3 
- سیستم‌عامل (Android)
- TargetSDK/CompileSDK (Android) : 32

</div>

**Comment by mdpe-ir** [comment]
بعد از دیباگ های انجام شده متوجه شدم که پوشه هنوز با فلاتر 3 و نسخه های جاوا 18 و 17 سازگار نیست . 
با محیط توسعه ی فلاتر 2.10.5 و جاوای 11 پلاگین پوشه بدون مشکل بالا بیلد شد . 
امید وارم که به زودی پلاگین پوشه با نسخه ی جدید فریم ورک فلاتر سازگار شود.

**Comment by mahdi-malv** [comment]
سلام
ممنونم بابت اینکه reproduction case کاملی گذاشتید
حتما توی ریلیز بعدی رفع مشکل خواهد شد

ایشو باز میمونه تا آپدیت بشه
باتشکر

**Comment by esmmusavi** [comment]
@mahdi-malv لطفا اطلاع رسانی کنید که بروز رسانی کی انجام می شه

**Comment by mahdi-malv** [comment]
@esmmusavi 
بابت تاخیر عذر میخوام. تسکش WIP هست و در حال انجامه
مشکل به این دلیل هست که APIهای قدیمی استفاده شده برای backgroundIsolation توی پلاگین حذف یا عوض شده. کلا روش هندل‌کردنش باید عوض بشه.
ایشو رو در اولین ریلیز آلفا آپدیت خواهم کرد

**Comment by mahdi-malv** [comment]
لطفا نسخه‌ی ۲.۶.۱ رو تست کنید و به بنده اطلاع بدید
با تشکر
@mdpe-ir

**Comment by mdpe-ir** [comment]
خسته نباشید.
نسخه ی 2.6.1 تست شد و مشکل به صورت کامل برطرف گردیده است . @mahdi-malv 

اطلاعات محیط تست:

- نسخه‌ی پوشه  : pushe_flutter: ^2.6.1
- نسخه‌ی فریم‌ورک : Flutter 3.0.5 • channel stable
- سیستم‌عامل (Android)
- TargetSDK/CompileSDK (Android) : 33
- نسخه ی کاتلین :‌ 1.6.10
