### ISSUE TITLE
MissingPluginException error on iOS devices

### ISSUE THREAD

**Issue by p4yam** [pusheco/pushe-flutter#6]
سلام.
ما با استفاده از داکیومنت فلاتر پوشه، اون رو توی اپ خودمون پیاده سازی کردیم. پوشه توی دیوایس های اندرویدی به راحتی کار می کنه و مشکلی نداره اما توی ios ارور زیر رو میده:
`[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method Pushe#initialize on channel Pushe)`

ما توی پنل فقط یک اپ فلاتر تعریف کردیم. آیا برای ios باید یک اپ جدا تعریف بشه یا همون کافیه؟

**Comment by payam-zahedi** [comment]
متاسفانه پلاگین پوشه برای ios تعریف نشده.
 در واقع من وقتی کد هاشون رو نگاه کردم فقط پیاده سازی اندروید رو اضافه کردن.

**Comment by amirhaa** [comment]
@payam-zahedi 

<div dir="rtl">

کتابخانه **iOS** را به تازگی بازنویسی کرده ایم و به زودی در **Flutter** هم پشتیبانی از **iOS** را اضافه میکنیم

</div>

**Comment by mahdi-malv** [comment]
iOS support is added in version `2.4.0`

https://pub.dev/packages/pushe_flutter/changelog#240
