### ISSUE TITLE
Support for ios devices.

### ISSUE THREAD

**Issue by erfanhemmati** [pusheco/pushe-flutter#8]
does this package support for ios devices ?
@mahdi-malv 
@amirhaa

**Comment by mahdi-malv** [comment]
Hey

We are currently working on it. Soon it'll be ready, but the current version does not support iOS.

**Comment by mahdi-malv** [comment]
#6

**Comment by Sepehr13** [comment]
Any update on this?

**Comment by mahdi-malv** [comment]
`iOS` support is added as of **`2.4.0`**

https://pub.dev/packages/pushe_flutter/changelog#240
